
name: .NET CI


on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report & Quality Gate
      run: |
        reportgenerator
        -reports:"**/coverage.cobertura.xml"
        -targetdir:"coveragereport"
        -reporttypes:Html_Dark
        -thresholds:70